name: Release

on:
  workflow_dispatch:
    gh_release:
      description: 'Release on GitHub'
      required: false
      type: boolean
    py_release:
      description: 'Release on PyPI'
      required: false
      type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    name: Release to PYPI ðŸš€
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build package distributions with Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v8.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: steps.release.outputs.released == 'true' && github.event.inputs.py_release == 'true'

    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/upload-to-gh-release@main
      if: steps.release.outputs.released == 'true' && github.event.inputs.gh_release == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}