name: Test and Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        include:
          - python-version: 3.6
            django-version: Django<=2.3

          - python-version: 3.6
            django-version: Django<=3.3

          - python-version: 3.7
            django-version: Django<=2.3

          - python-version: 3.7
            django-version: Django<=3.3

          - python-version: 3.8
            django-version: Django<=2.3

          - python-version: 3.9
            django-version: Django<=3.3

    name: Test on Python ${{ matrix.python-version }} ${{ matrix.django-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ðŸ
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies ðŸ“¦
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install ${{ matrix.django-version }}
    - name: Test with pytest and calculate coverage ðŸ§ª
      run: |
        make test
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
